### ISSUE TITLE
Is there a reference sheet of all available emojis?

### ISSUE THREAD

**Issue by JarLowrey** [5t111111/middleman-emojifire#1]
I tried using this - https://www.webpagefx.com/tools/emoji-cheat-sheet/ but noticed that some didn't work, :simple_smile: for example.

**Comment by 5t111111** [comment]
Since this extension uses [gemoji](https://github.com/github/gemoji) for replacing aliases with emojis, available emojis are limited to the ones that defined in gemoji's database.

Gemoji refers to [this json](https://github.com/github/gemoji/blob/3f6057146c9a12e154c7bf00be4b125a76f413e0/db/emoji.json) to link aliases to emojis, so I am sure that you can use it as a reference sheet as well.

Note that since this extension does not intend to fix gemoji to a specific version, that json might change in future update.

**Comment by JarLowrey** [comment]
Cool, thank you. 

Also want to note that although the cheat sheet lists :simple_smile: as a valid emoji it obviously isn't working on GitHub, so that was a bad source anyways.

**Comment by 5t111111** [comment]
Welcome!
Yes, I used to use the cheet sheet too, but I found it was not appropriate for use on GitHub 🤔
